# Copyright 2026 Limx Dynamics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

"""Cosmos3-Edge post-training on LIBERO-Spatial."""

eval = dict(
    dataset=dict(
        extra_tensor_keys=[
            'conditioning_fps',
            'prepend_state_to_action',
        ],
        img_buffer_len=1,
        transforms=[
            dict(
                embodiment_id=5,
                img_keys=[
                    'agentview_image',
                    'robot0_eye_in_hand_image',
                ],
                type='ProcessLiberoEvalInputs'),
            dict(
                conditioning_fps=20.0,
                prepend_state_to_action=False,
                type='SetCosmos3ActionMetadata'),
            dict(
                image_resize_strategy='resize-naive',
                input_sizes=[
                    [
                        3,
                        128,
                        128,
                    ],
                    [
                        3,
                        128,
                        128,
                    ],
                ],
                means=[
                    [
                        127.5,
                        127.5,
                        127.5,
                    ],
                    [
                        127.5,
                        127.5,
                        127.5,
                    ],
                ],
                stds=[
                    [
                        127.5,
                        127.5,
                        127.5,
                    ],
                    [
                        127.5,
                        127.5,
                        127.5,
                    ],
                ],
                type='TransformImage'),
            dict(
                action_metadata=dict(
                    append_viewpoint=False,
                    conditioning_fps=20.0,
                    frame_window_size=17,
                    video_height=256,
                    video_width=128),
                cfg_dropout_rate=0.0,
                max_len=512,
                output_attention_mask_key='lang_masks',
                output_key='lang_tokens',
                tokenizer=dict(
                    model_max_length=4096,
                    model_path='./checkpoints/Cosmos3-Edge',
                    padding_side='right',
                    trust_remote_code=True,
                    type='PretrainedTokenizer'),
                type='ProcessCosmos3Prompt'),
            dict(
                gripper_key='robot0_gripper_qpos',
                norm_type='mean_std',
                out_key='states',
                pos_key='robot0_eef_pos',
                quat_key='robot0_eef_quat',
                state_dim=64,
                type='LiberoProprioFromInputs'),
            dict(frame_window_size=1, num_views=2, type='PrepareVideo'),
        ],
        type='LiberoParquetEvalDataset'),
    denormalize_action=dict(
        action_dim=7, norm_type='mean_std', type='DenormalizeLiberoAction'),
    enable_mixed_precision_training=True,
    eval_chunk_size=10,
    inference_seed=7,
    mixed_precision_dtype='bf16',
    model_family='cosmos3',
    norm_stats_key='libero_spatial_no_noops',
    num_inference_steps=30,
    num_steps_wait=10,
    num_trials_per_task=50,
    resize_size=128,
    seed=7,
    task_ids=None,
    task_suite_name='libero_spatial',
    type='LiberoEvalRunner')
inference_model = dict(
    action_horizon=16,
    action_in_proj=dict(
        input_size=64,
        num_domains=32,
        output_size=2048,
        type='DomainAwareLinear'),
    action_out_proj=dict(
        input_size=2048,
        num_domains=32,
        output_size=64,
        type='DomainAwareLinear'),
    base_fps=24.0,
    enable_fps_modulation=True,
    enable_vision_loss=True,
    freeze_non_moe_vlm_backbone=True,
    freeze_vlm_backbone=False,
    latent_patch_size=2,
    max_action_dim=64,
    name_mapping=dict({
        '.self_attn.k_norm_moe_gen.':
        '.self_attn.norm_added_k.',
        '.self_attn.k_proj.':
        '.self_attn.to_k.',
        '.self_attn.k_proj_moe_gen.':
        '.self_attn.add_k_proj.',
        '.self_attn.o_proj.':
        '.self_attn.to_out.',
        '.self_attn.o_proj_moe_gen.':
        '.self_attn.to_add_out.',
        '.self_attn.q_norm_moe_gen.':
        '.self_attn.norm_added_q.',
        '.self_attn.q_proj.':
        '.self_attn.to_q.',
        '.self_attn.q_proj_moe_gen.':
        '.self_attn.add_q_proj.',
        '.self_attn.v_proj.':
        '.self_attn.to_v.',
        '.self_attn.v_proj_moe_gen.':
        '.self_attn.add_v_proj.',
        'action_in_proj.':
        'action_proj_in.',
        'action_modality_embed.weight':
        'action_modality_embed',
        'action_out_proj.':
        'action_proj_out.',
        'time_embedder.mlp.0.':
        'time_embedder.linear_1.',
        'time_embedder.mlp.2.':
        'time_embedder.linear_2.',
        'vision_in_proj.projector.':
        'proj_in.',
        'vision_out_proj.projector.':
        'proj_out.',
        'vlm_backbone.lm_head.weight':
        'lm_head.weight',
        'vlm_backbone.model.language_model.embed_tokens.weight':
        'embed_tokens.weight',
        'vlm_backbone.model.language_model.layers.':
        'layers.',
        'vlm_backbone.model.language_model.norm.weight':
        'norm.weight',
        'vlm_backbone.model.language_model.norm_moe_gen.weight':
        'norm_moe_gen.weight'
    }),
    num_embodiment_domains=32,
    ori_action_dim=7,
    packed_attention_backend='flash2',
    position_embedding_type='unified_3d_mrope',
    pretrained_name_or_path='./checkpoints/Cosmos3-Edge/transformer',
    rectified_flow_inference_config=dict(
        num_steps=30,
        num_train_timesteps=1000,
        scheduler_type='unipc',
        shift=10.0,
        use_dynamic_shifting=False,
        use_karras_sigmas=False),
    rectified_flow_training_config=dict(
        action_loss_weight=10.0,
        independent_action_schedule=False,
        normalize_loss_by_active=False,
        shift=dict({
            '256': 3,
            '480': 5,
            '720': 10
        }),
        shift_action=None,
        train_time_action_distribution='logitnormal',
        train_time_image_distribution='logitnormal',
        train_time_video_distribution='waver',
        train_time_weight='uniform',
        use_discrete_rf=False,
        use_dynamic_shift=False,
        use_high_sigma_strategy=False,
        use_high_sigma_strategy_action=False,
        vision_loss_weight=1.0),
    special_tokens=dict(
        end_of_generation=21, eos_token_id=11, start_of_generation=20),
    strict_mapping=True,
    timestep_scale=0.001,
    type='Cosmos3FlowMatching',
    unified_3d_mrope_reset_spatial_ids=True,
    unified_3d_mrope_temporal_modality_margin=15000,
    vision_in_proj=dict(in_dim=192, out_dim=2048, type='LinearProjector'),
    vision_latent_dim=48,
    vision_out_proj=dict(in_dim=2048, out_dim=192, type='LinearProjector'),
    vision_vae=dict(
        encode_exact_durations=[
            17,
        ],
        pretrained_name_or_path='./checkpoints/Wan2.2-TI2V-5B/Wan2.2_VAE.pth',
        type='Cosmos3Wan22VAE'),
    vlm_backbone=dict(
        include_visual=False,
        skip_init_weights=True,
        type='Cosmos3MoTBackbone',
        vlm_config=dict(
            attention_bias=False,
            bos_token_id=1,
            enable_mrope=True,
            eos_token_id=11,
            head_dim=128,
            hidden_size=2048,
            intermediate_size=9216,
            layer_norm_epsilon=1e-05,
            max_position_embeddings=131072,
            mlp_bias=False,
            mlp_hidden_act='relu2',
            model_type='nemotron_3_dense_vl_text',
            mrope_section=[
                24,
                20,
                20,
            ],
            num_attention_heads=16,
            num_hidden_layers=28,
            num_key_value_heads=8,
            pad_token_id=11,
            rope_theta=100000000.0,
            tie_word_embeddings=False,
            use_und_k_norm_for_gen=True,
            vocab_size=131072)))
model = dict(
    action_horizon=16,
    action_in_proj=dict(
        input_size=64,
        num_domains=32,
        output_size=2048,
        type='DomainAwareLinear'),
    action_out_proj=dict(
        input_size=2048,
        num_domains=32,
        output_size=64,
        type='DomainAwareLinear'),
    base_fps=24.0,
    enable_fps_modulation=True,
    enable_vision_loss=True,
    freeze_non_moe_vlm_backbone=True,
    freeze_vlm_backbone=False,
    latent_patch_size=2,
    max_action_dim=64,
    name_mapping=dict({
        '.self_attn.k_norm_moe_gen.':
        '.self_attn.norm_added_k.',
        '.self_attn.k_proj.':
        '.self_attn.to_k.',
        '.self_attn.k_proj_moe_gen.':
        '.self_attn.add_k_proj.',
        '.self_attn.o_proj.':
        '.self_attn.to_out.',
        '.self_attn.o_proj_moe_gen.':
        '.self_attn.to_add_out.',
        '.self_attn.q_norm_moe_gen.':
        '.self_attn.norm_added_q.',
        '.self_attn.q_proj.':
        '.self_attn.to_q.',
        '.self_attn.q_proj_moe_gen.':
        '.self_attn.add_q_proj.',
        '.self_attn.v_proj.':
        '.self_attn.to_v.',
        '.self_attn.v_proj_moe_gen.':
        '.self_attn.add_v_proj.',
        'action_in_proj.':
        'action_proj_in.',
        'action_modality_embed.weight':
        'action_modality_embed',
        'action_out_proj.':
        'action_proj_out.',
        'time_embedder.mlp.0.':
        'time_embedder.linear_1.',
        'time_embedder.mlp.2.':
        'time_embedder.linear_2.',
        'vision_in_proj.projector.':
        'proj_in.',
        'vision_out_proj.projector.':
        'proj_out.',
        'vlm_backbone.lm_head.weight':
        'lm_head.weight',
        'vlm_backbone.model.language_model.embed_tokens.weight':
        'embed_tokens.weight',
        'vlm_backbone.model.language_model.layers.':
        'layers.',
        'vlm_backbone.model.language_model.norm.weight':
        'norm.weight',
        'vlm_backbone.model.language_model.norm_moe_gen.weight':
        'norm_moe_gen.weight'
    }),
    num_embodiment_domains=32,
    ori_action_dim=7,
    packed_attention_backend='flash2',
    position_embedding_type='unified_3d_mrope',
    pretrained_name_or_path='./checkpoints/Cosmos3-Edge/transformer',
    rectified_flow_inference_config=dict(
        num_steps=30,
        num_train_timesteps=1000,
        scheduler_type='unipc',
        shift=10.0,
        use_dynamic_shifting=False,
        use_karras_sigmas=False),
    rectified_flow_training_config=dict(
        action_loss_weight=10.0,
        independent_action_schedule=False,
        normalize_loss_by_active=False,
        shift=dict({
            '256': 3,
            '480': 5,
            '720': 10
        }),
        shift_action=None,
        train_time_action_distribution='logitnormal',
        train_time_image_distribution='logitnormal',
        train_time_video_distribution='waver',
        train_time_weight='uniform',
        use_discrete_rf=False,
        use_dynamic_shift=False,
        use_high_sigma_strategy=False,
        use_high_sigma_strategy_action=False,
        vision_loss_weight=1.0),
    special_tokens=dict(
        end_of_generation=21, eos_token_id=11, start_of_generation=20),
    strict_mapping=True,
    timestep_scale=0.001,
    type='Cosmos3FlowMatching',
    unified_3d_mrope_reset_spatial_ids=True,
    unified_3d_mrope_temporal_modality_margin=15000,
    vision_in_proj=dict(in_dim=192, out_dim=2048, type='LinearProjector'),
    vision_latent_dim=48,
    vision_out_proj=dict(in_dim=2048, out_dim=192, type='LinearProjector'),
    vision_vae=dict(
        encode_exact_durations=[
            17,
        ],
        pretrained_name_or_path='./checkpoints/Wan2.2-TI2V-5B/Wan2.2_VAE.pth',
        type='Cosmos3Wan22VAE'),
    vlm_backbone=dict(
        include_visual=False,
        skip_init_weights=True,
        type='Cosmos3MoTBackbone',
        vlm_config=dict(
            attention_bias=False,
            bos_token_id=1,
            enable_mrope=True,
            eos_token_id=11,
            head_dim=128,
            hidden_size=2048,
            intermediate_size=9216,
            layer_norm_epsilon=1e-05,
            max_position_embeddings=131072,
            mlp_bias=False,
            mlp_hidden_act='relu2',
            model_type='nemotron_3_dense_vl_text',
            mrope_section=[
                24,
                20,
                20,
            ],
            num_attention_heads=16,
            num_hidden_layers=28,
            num_key_value_heads=8,
            pad_token_id=11,
            rope_theta=100000000.0,
            tie_word_embeddings=False,
            use_und_k_norm_for_gen=True,
            vocab_size=131072)))
runner = dict(
    change_key_name=False,
    collator=dict(
        list_keys=[
            'sequence_plan',
        ],
        meta_keys=[
            'task_description',
            'stats',
            'info',
            'timestamp',
        ],
        pad_id=11,
        sequence_keys=[
            'text_token_ids',
        ],
        tensor_keys=[
            'images',
            'actions',
            'embodiment_ids',
            'raw_action_dim',
            'conditioning_fps',
            'action_fps',
        ],
        type='Cosmos3Collator'),
    enable_gradient_checkpointing=True,
    enable_mixed_precision_training=True,
    grad_accumulation_steps=1,
    lr_scheduler=dict(type='linear-warmup+cosine-decay', warmup_ratio=0.0),
    max_epochs=12,
    max_grad_norm=1.0,
    max_keep_ckpts=2,
    max_steps=None,
    metric=dict(
        active_trackers=(
            'jsonl',
            'wandb',
        ),
        grad_accumulation_steps=1,
        run_dir='work_dirs',
        type='VLAMetric',
        window_size=1),
    mixed_precision_dtype='bf16',
    optimizer=dict(
        betas=(
            0.9,
            0.99,
        ),
        eps=1e-08,
        fused=True,
        lr=0.0001,
        paramwise_learning_rate=dict(),
        type='AdamW',
        weight_decay=0.05),
    sampler=None,
    save_epoch_interval=1,
    save_iter_interval=10000,
    sharding_strategy='full-shard',
    tokenizer=dict(
        model_max_length=4096,
        model_path='./checkpoints/Cosmos3-Edge',
        padding_side='right',
        trust_remote_code=True,
        type='PretrainedTokenizer'),
    type='FSDPTrainRunner')
seed = 7
train_dataloader = dict(
    dataset=dict(
        datasets=dict(
            action_key='action',
            action_window_size=16,
            data_root_path=
            '/mnt/data/cpfs/mnt/data/yanis/FastWAM/data/libero_mujoco3.3.2/libero_spatial_no_noops_lerobot',
            frame_window_size=17,
            require_full_window=True,
            statistic_name='libero_spatial_no_noops',
            transforms=[
                dict(
                    embodiment_id=5,
                    name_mappings=dict({
                        'actions': [
                            'actions',
                        ],
                        'observation.state': [
                            'states',
                        ]
                    }),
                    parquet_keys=[
                        'observation.state',
                        'timestamp',
                        'actions',
                        'info',
                        'stats',
                    ],
                    type='ProcessParquetInputs',
                    video_keys=[
                        'observation.images.image',
                        'observation.images.wrist_image',
                    ]),
                dict(
                    action_metadata=dict(
                        append_viewpoint=False,
                        conditioning_fps=20.0,
                        frame_window_size=17,
                        video_height=256,
                        video_width=128),
                    cfg_dropout_rate=0.1,
                    max_len=512,
                    tokenizer=dict(
                        model_max_length=4096,
                        model_path='./checkpoints/Cosmos3-Edge',
                        padding_side='right',
                        trust_remote_code=True,
                        type='PretrainedTokenizer'),
                    type='ProcessCosmos3Prompt'),
                dict(height=128, type='ResizeImages', width=128),
                dict(type='SimpleNormalizeImages'),
                dict(
                    action_dim=64,
                    action_key='action',
                    norm_type='mean_std',
                    state_dim=64,
                    state_key='proprio',
                    type='NormalizeStatesAndActions'),
                dict(
                    conditioning_fps=20.0,
                    frame_window_size=17,
                    mode='joint',
                    prepend_state_to_action=False,
                    raw_action_dim=7,
                    type='BuildCosmos3Sequence'),
                dict(frame_window_size=17, num_views=2, type='PrepareVideo'),
            ],
            type='ParquetDataset',
            use_delta=False,
            window_start_idx=0),
        name_mappings=dict({
            'action': [
                'action',
            ],
            'observation.state': [
                'proprio',
            ]
        }),
        statistic_keys=[
            'observation.state',
            'timestamp',
            'action',
        ],
        statistic_name='libero_spatial_no_noops',
        type='DistributedRepeatingDataset'),
    per_device_batch_size=8,
    per_device_num_workers=4)
